#!/bin/sh
### BEGIN INIT INFO
# Provides: neo4j
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Graph database neo4j
# Description: Neo4j graph database preconfigured for Open Semantic Search.
### END INIT INFO

start () {
    echo -n "Starting Neo4j server ..."

    su neo4j -c "/opt/neo4j/bin/neo4j start"
    RETVAL=$?
    if [ $RETVAL = 0 ]
    then
        echo "done."
    else
        echo "failed. See error code for more information."
    fi
    return $RETVAL
}

stop () {
    # Stop daemon
    echo -n "Stopping Neo4j server ..."

    su neo4j -c "/opt/neo4j/bin/neo4j stop"

    RETVAL=$?

    if [ $RETVAL = 0 ]
    then
        echo "Done."
    else
        echo "Failed. See error code for more information."
    fi
    return $RETVAL
}

restart () {
    su neo4j -c "/opt/neo4j/bin/neo4j restart"
}

status () {
    # Report on the status of the daemon
    su neo4j -c "/opt/neo4j/bin/neo4j status"
    return $?
}

case "$1" in
    start)
        start
    ;;
    status)
        status
    ;;
    stop)
        stop
    ;;
    restart)
        restart
    ;;
    *)
        echo $"Usage: neo4j {start|status|stop|restart}"
        exit 3
    ;;
esac

exit $RETVAL
